#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
# RIPPED FROM: https://github.com/curtisallen/openshift-yeoman/blob/master/.openshift/action_hooks/build

# Install our gems needed for yeomen
if [ ! -d $OPENSHIFT_DATA_DIR/gems ]; then
	echo "Making Gems dir"
	mkdir $OPENSHIFT_DATA_DIR/gems
fi

export GEM_HOME=$OPENSHIFT_DATA_DIR/gems
if [ `gem list compass -i` == 'false' ]; then
	echo "Install Gems"
	gem install compass 
fi